{
 "title": "Test-Cluster-TiKV-CDC",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": "label_values(go_goroutines, tidb_cluster)"
   },
   {
    "name": "changefeed",
    "label": "Changefeed",
    "query": "label_values(tikv_cdc_processor_resolved_ts{tidb_cluster=\"$tidb_cluster\"}, changefeed)"
   },
   {
    "name": "capture",
    "label": "TiKV-CDC",
    "query": "label_values(process_start_time_seconds{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"}, instance)"
   },
   {
    "name": "tikv_instance",
    "label": "TiKV",
    "query": "label_values(tikv_engine_size_bytes{tidb_cluster=\"$tidb_cluster\"}, instance)"
   },
   { "name": "spike_threshold", "label": "Latency spike (s) >", "query": "1, 3, 5, 10, 60, 300" },
   {
    "name": "runtime_instance",
    "label": "Runtime metrics",
    "query": "label_values(process_start_time_seconds{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "description": "Uptime of TiKV-CDC and TiKV",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"})",
       "legendFormat": "TiKV-CDC-{{instance}}"
      },
      {
       "expr": "(time() - process_start_time_seconds{tidb_cluster=\"$tidb_cluster\", job=\"tikv\"})",
       "legendFormat": "TiKV-{{instance}}"
      },
      {
       "expr": "(time() - process_start_time_seconds{tidb_cluster=\"$tidb_cluster\", job=\"pd\"})",
       "legendFormat": "PD-{{instance}}"
      }
     ]
    },
    {
     "title": "Goroutine count",
     "type": "graph",
     "description": "Goroutine count of TiKV-CDC",
     "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " go_goroutines{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Open FD count",
     "type": "graph",
     "description": "The count of open FD count of TiKV-CDC",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ownership",
     "type": "table",
     "description": "TiKV-CDC cluster ownership status",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
     "targets": [
      {
       "expr": "rate(tikv_cdc_owner_ownership_counter{tidb_cluster=\"$tidb_cluster\"}[30s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "description": "CPU usage of TiKV-CDC",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"}[1m])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "tikv_cdc_server_go_max_procs{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"}",
       "legendFormat": "{{instance}}-MaxProcs"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "description": "Memory usage of TiKV-CDC",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"}",
       "legendFormat": "process-{{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"}",
       "legendFormat": "heap-{{instance}}"
      }
     ]
    },
    {
     "title": "Ownership history",
     "type": "graph",
     "description": "The history of TiKV-CDC cluster ownership, owner node has a value that is great than 0",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_owner_ownership_counter{tidb_cluster=\"$tidb_cluster\"}[30s])) by (instance) > BOOL 0.5",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "PD leader history",
     "type": "graph",
     "description": "The history of PD cluster leadership, leader node has a value that is great than 0",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_tso_role{tidb_cluster=\"$tidb_cluster\", dc=\"global\"} > BOOL 0.5",
       "legendFormat": "PD-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Changefeed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Changefeed table count",
     "type": "table",
     "description": "The number of captured table of TiKV-CDC nodes ",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(tikv_cdc_processor_num_of_tables{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Processor resolved ts",
     "type": "table",
     "description": "Internal resolved ts of TiKV-CDC nodes",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 3 },
     "targets": [
      {
       "expr": "max(tikv_cdc_processor_resolved_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture,changefeed)",
       "legendFormat": "{{capture}}-{{changefeed}}"
      },
      {
       "expr": "max(tikv_cdc_processor_checkpoint_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture,changefeed) > 0",
       "legendFormat": "checkpoint-{{capture}}-{{changefeed}}"
      }
     ]
    },
    {
     "title": "Table resolved ts",
     "type": "table",
     "description": "Internal resolved ts of captured tables",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 3 },
     "targets": [
      {
       "expr": "bottomk(10, max(tikv_cdc_processor_table_resolved_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture,changefeed,table))",
       "legendFormat": "{{capture}}-{{changefeed}}-{{table}}"
      },
      {
       "expr": "bottomk(10, max(tikv_cdc_processor_checkpoint_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture,changefeed,table) > 0)",
       "legendFormat": "checkpoint-{{capture}}-{{changefeed}}"
      }
     ]
    },
    {
     "title": "Table count maintained by owner",
     "type": "table",
     "description": "The number of replicated tables maintained in owner",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(tikv_cdc_owner_maintain_table_num{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\",type=\"total\"}) by (capture)",
       "legendFormat": "{{capture}}-total"
      },
      {
       "expr": "sum(tikv_cdc_owner_maintain_table_num{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\",type=\"wip\"}) by (capture)",
       "legendFormat": "{{capture}}-wip"
      }
     ]
    },
    {
     "title": "Changefeed checkpoint",
     "type": "graph",
     "description": "The checkpoint ts of changefeeds.",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "max(pd_cluster_tso{tidb_cluster=\"$tidb_cluster\"})",
       "legendFormat": "approximate current time (s)"
      },
      {
       "expr": "max(tikv_cdc_owner_checkpoint_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed) > 0",
       "legendFormat": "{{changefeed}}"
      }
     ]
    },
    {
     "title": "PD etcd requests/s",
     "type": "graph",
     "description": "Request count of etcd operation per second",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_etcd_request_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (capture, type)",
       "legendFormat": "{{capture}}-{{type}}"
      }
     ]
    },
    {
     "title": "Exit error count/m",
     "type": "graph",
     "description": "The number of errors that interrupt changefeed per minute ",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(tikv_cdc_processor_exit_with_error_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Changefeed checkpoint lag",
     "type": "graph",
     "description": "The lag between changefeed checkpoint ts and the latest ts of upstream TiDB.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(tikv_cdc_owner_checkpoint_ts_lag{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed)",
       "legendFormat": "{{changefeed}}"
      },
      {
       "expr": "sum(tikv_cdc_processor_checkpoint_ts_lag{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}) by (capture,changefeed)",
       "legendFormat": "{{changefeed}}-{{capture}}"
      },
      {
       "expr": "max(tikv_cdc_owner_resolved_ts_lag{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed)",
       "legendFormat": "{{changefeed}}-resolvedts"
      },
      {
       "expr": "sum(tikv_cdc_processor_resolved_ts_lag{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}) by (capture,changefeed)",
       "legendFormat": "{{changefeed}}-{{capture}}-resolvedts"
      }
     ]
    },
    {
     "title": "Changefeed checkpoint derivative",
     "type": "graph",
     "description": "The derivative of a changefeed checkpoint, ideally it should not be 0 (means the changefeed is stopped).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(tikv_cdc_owner_checkpoint_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (changefeed) / 1000 > 0",
       "legendFormat": "{{changefeed}}"
      }
     ]
    },
    {
     "title": "The status of changefeeds",
     "type": "graph",
     "description": "The status of each changefeed.\n\n0: Normal\n\n1: Error\n\n2: Failed\n\n3: Stopped\n\n4: Finished\n\n-1: Unknown",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tikv_cdc_owner_status{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}",
       "legendFormat": "{{changefeed}}"
      }
     ]
    },
    {
     "title": "Changefeed checkpoint catch-up ETA",
     "type": "graph",
     "description": "Estimate the remaining time for a changefeed catch-up upstream TiDB.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "abs(max(tikv_cdc_owner_checkpoint_ts_lag{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"} / (deriv(tikv_cdc_owner_checkpoint_ts{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])/1000)) by (changefeed))",
       "legendFormat": "{{changefeed}}"
      }
     ]
    },
    {
     "title": "Sink write duration",
     "type": "heatmap",
     "description": "Sink write duration of changefeeds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "max(rate(tikv_cdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sink write duration percentile",
     "type": "graph",
     "description": "Percentiles of sink write duration of changefeeds",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_cdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p999"
      }
     ]
    },
    {
     "title": "Sink write rows count/s",
     "type": "graph",
     "description": "The number of changed rows that are written to  downstream per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (rate(tikv_cdc_sink_txn_batch_size_sum{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}"
      },
      {
       "expr": "sum (rate(tikv_cdc_sink_txn_batch_size_sum{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (changefeed)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Sink write batch size percentile",
     "type": "graph",
     "description": "Percentiles of sink batch size",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(tikv_cdc_sink_txn_batch_size_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_sink_txn_batch_size_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p99"
      }
     ]
    },
    {
     "title": "Flush sink duration",
     "type": "heatmap",
     "description": "Asynchronous flush sink duration of changefeeds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "max(rate(tikv_cdc_sink_flush_event_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Flush sink duration percentile",
     "type": "graph",
     "description": "Percentiles of asynchronous flush sink duration of changefeeds",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_sink_flush_event_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance,type))",
       "legendFormat": "{{instance}}-{{type}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_sink_flush_event_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance,type))",
       "legendFormat": "{{instance}}-{{type}}-p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_cdc_sink_flush_event_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (le,instance,type))",
       "legendFormat": "{{instance}}-{{type}}-p999"
      }
     ]
    },
    {
     "title": "MySQL sink conflict detect duration",
     "type": "heatmap",
     "description": "The duration of detecting and waiting conflict of MySQL sink",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "max(rate(tikv_cdc_sink_conflict_detect_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "MySQL sink worker load",
     "type": "graph",
     "description": "Distribution of MySQL worker loads",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(rate(tikv_cdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) <= 2)",
       "legendFormat": "0-2 row/s worker"
      },
      {
       "expr": "count(rate(tikv_cdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) > 2 and rate(tikv_cdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) <= 10)",
       "legendFormat": "2-10 row/s worker"
      },
      {
       "expr": "count(rate(tikv_cdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) > 10 and rate(tikv_cdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) <= 100)",
       "legendFormat": "10-100 row/s worker"
      },
      {
       "expr": "count(rate(tikv_cdc_sink_bucket_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m]) > 100)",
       "legendFormat": ">100 row/s worker"
      }
     ]
    },
    {
     "title": "MySQL sink ddl execution duration",
     "type": "heatmap",
     "description": "The duration of executing DDL in MySQL sink",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "max(rate(tikv_cdc_sink_ddl_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "MySQL sink conflict detect duration percentile",
     "type": "graph",
     "description": "Percentiles of detecting and waiting conflict duration of MySQL sink",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95,sum(rate(tikv_cdc_sink_conflict_detect_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99,sum(rate(tikv_cdc_sink_conflict_detect_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p99"
      },
      {
       "expr": "histogram_quantile(0.999,sum(rate(tikv_cdc_sink_conflict_detect_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p999"
      }
     ]
    },
    {
     "title": "Processor Memory Consumption Per Capture",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_processor_table_memory_consumption_sum{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[30s]) / rate(tikv_cdc_processor_table_memory_consumption_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[30s])) by (capture)",
       "legendFormat": "{{ capture }}"
      }
     ]
    },
    {
     "title": "MySQL sink ddl execution duration percentile",
     "type": "graph",
     "description": "Percentiles of executing DDL duration of MySQL sink",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95,sum(rate(tikv_cdc_sink_ddl_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99,sum(rate(tikv_cdc_sink_ddl_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p99"
      },
      {
       "expr": "histogram_quantile(0.999,sum(rate(tikv_cdc_sink_ddl_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "{{instance}}-p999"
      }
     ]
    },
    {
     "title": "Processor Memory Consumption Per Changefeed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_processor_table_memory_consumption_sum{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[30s]) / rate(tikv_cdc_processor_table_memory_consumption_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[30s])) by (capture, changefeed)",
       "legendFormat": "{{ capture }}-{{ changefeed }}"
      }
     ]
    },
    {
     "title": "Schema Storage GC progress",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
     "targets": [
      {
       "expr": "tikv_cdc_processor_schema_storage_gc_ts{changefeed=~\"$changefeed\", capture=~\"$capture\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataflow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Puller output events/s",
     "type": "graph",
     "description": "The number of events that puller outputs to sorter \n per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (rate(tikv_cdc_puller_txn_collect_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (changefeed, capture, type)",
       "legendFormat": "{{changefeed}}-{{capture}}-{{type}}"
      }
     ]
    },
    {
     "title": "Puller output events",
     "type": "graph",
     "description": "The total number of events that puller outputs",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_puller_txn_collect_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}) by (changefeed, capture, type)",
       "legendFormat": "{{changefeed}}-{{capture}}-{{type}}"
      }
     ]
    },
    {
     "title": "Sorter output events/s",
     "type": "graph",
     "description": "The number of events that sorter outputs to puller \n per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (changefeed, capture, type)",
       "legendFormat": "{{changefeed}}-{{capture}}-{{type}}"
      }
     ]
    },
    {
     "title": "Sorter output events",
     "type": "graph",
     "description": "The total number of events that sorter outputs",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_sorter_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}) by (capture, changefeed, type)",
       "legendFormat": "{{changefeed}}-{{capture}}-{{type}}"
      }
     ]
    },
    {
     "title": "Table sink output events/s",
     "type": "graph",
     "description": "The number of events that table sorter outputs to buffer sink per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sink_table_sink_total_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (changefeed, capture)",
       "legendFormat": "{{changefeed}}-{{capture}}"
      }
     ]
    },
    {
     "title": "Table sink output events",
     "type": "graph",
     "description": "The total number of events that table sinks emit",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_sink_table_sink_total_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}) by (changefeed, capture)",
       "legendFormat": "{{changefeed}}-{{capture}}"
      }
     ]
    },
    {
     "title": "Buffer sink output events/s",
     "type": "graph",
     "description": "The total number of events that buffer sink outputs to backend sink per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sink_buffer_sink_total_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (changefeed, capture)",
       "legendFormat": "{{changefeed}}-{{capture}}"
      }
     ]
    },
    {
     "title": "Buffer sink output events",
     "type": "graph",
     "description": "The total number of events that buffer sink emits",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_sink_buffer_sink_total_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}) by (changefeed, capture)",
       "legendFormat": "{{changefeed}}-{{capture}}"
      }
     ]
    },
    {
     "title": "Sink output events/s",
     "type": "graph",
     "description": "The number of rows(events) that are processed by sink per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (rate(tikv_cdc_sink_total_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (changefeed, capture)",
       "legendFormat": "{{changefeed}}-{{capture}}"
      }
     ]
    },
    {
     "title": "Sink output events",
     "type": "graph",
     "description": "The number of rows(events) that are processed by sink",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_sink_total_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}) by (changefeed, capture)",
       "legendFormat": "{{changefeed}}-{{capture}}"
      }
     ]
    },
    {
     "title": "Sink flush rows/s",
     "type": "graph",
     "description": "The number of rows that sink flushes to downstream per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sink_total_flushed_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (changefeed, capture)",
       "legendFormat": "{{changefeed}}-{{capture}}"
      }
     ]
    },
    {
     "title": "Sink flush rows",
     "type": "graph",
     "description": "The number of rows(events) that are flushed by sink",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_sink_total_flushed_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed, capture)",
       "legendFormat": "{{changefeed}}-{{capture}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "On disk data size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_sorter_on_disk_data_size_gauge{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "In-memory data size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_sorter_in_memory_data_size_gauge{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Level files",
     "type": "graph",
     "description": "The count of files of each levels",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_db_level_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}) by (capture, level)",
       "legendFormat": "{{capture}}-{{level}}"
      }
     ]
    },
    {
     "title": "Write duration",
     "type": "heatmap",
     "description": "The time of sorter write",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_write_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Write speed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_write_bytes_sum{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}-sorter"
      },
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_write_bytes_total{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (capture) / sum(rate(tikv_cdc_sorter_db_write_bytes_sum{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}-amplification"
      },
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_write_bytes_total{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}-disk"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "description": "CPU usage of LevelDB sorter",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_actor_worker_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$capture\", name=~\"sorter|cleaner|compactor\"}[1m])) by (name, instance)",
       "legendFormat": "{{instance}}-{{name}}"
      },
      {
       "expr": "sum(rate(tikv_cdc_actor_worker_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$capture\", name=\"sorter\"}[1m])) by (name, id, instance)",
       "legendFormat": "{{instance}}-{{name}}-{{id}}"
      }
     ]
    },
    {
     "title": "Write bytes",
     "type": "heatmap",
     "description": "The time of sorter write",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_write_bytes_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Write OPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_write_bytes_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}-sorter"
      }
     ]
    },
    {
     "title": "Write delay",
     "type": "graph",
     "description": "The count and duration of write delay",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_db_write_delay_seconds{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}-duration"
      },
      {
       "expr": "sum(rate(tikv_cdc_db_write_delay_total{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}-count"
      }
     ]
    },
    {
     "title": "Read duration - First",
     "type": "heatmap",
     "description": "The time of sorter iterator read",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_iter_read_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\", call=\"first\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Read duration - Next",
     "type": "heatmap",
     "description": "The time of sorter iterator read",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_iter_read_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\", call=\"next\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Read duration - Release",
     "type": "heatmap",
     "description": "The time of sorter iterator read",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_iter_read_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\", call=\"release\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Read OPS - First",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_iter_read_duration_seconds_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\", call=\"first\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}-sorter"
      }
     ]
    },
    {
     "title": "Read OPS - Next",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_iter_read_duration_seconds_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\", call=\"next\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}-sorter"
      }
     ]
    },
    {
     "title": "Read OPS - Release",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_iter_read_duration_seconds_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\", call=\"release\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}-sorter"
      }
     ]
    },
    {
     "title": "Compact duration",
     "type": "heatmap",
     "description": "The time of sorter compact",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_db_compact_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eventfeed count",
     "type": "graph",
     "description": "The number of established Eventfeed RPC between TiKV-CDC and TiKV",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_kvclient_event_feed_count{tidb_cluster=\"$tidb_cluster\"}) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(grpc_client_started_total{tidb_cluster=\"$tidb_cluster\", grpc_method=\"EventFeed\"}) by (instance) - sum(grpc_client_handled_total{tidb_cluster=\"$tidb_cluster\", grpc_method=\"EventFeed\"}) by (instance)",
       "legendFormat": "{{instance}}-rpc"
      },
      {
       "expr": "sum(grpc_client_started_total{tidb_cluster=\"$tidb_cluster\", grpc_method=\"EventFeed\"}) by (instance)",
       "legendFormat": "{{instance}}-rpc-started"
      },
      {
       "expr": "sum(grpc_client_handled_total{tidb_cluster=\"$tidb_cluster\", grpc_method=\"EventFeed\"}) by (instance)",
       "legendFormat": "{{instance}}-rpc-handled"
      }
     ]
    },
    {
     "title": "Event size percentile",
     "type": "graph",
     "description": "Percentiles of Eventfeed message size",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_cdc_kvclient_event_size_bytes_bucket{tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, instance, type))",
       "legendFormat": "{{instance}}-{{type}}-p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_kvclient_event_size_bytes_bucket{tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, instance, type))",
       "legendFormat": "{{instance}}-{{type}}-p95"
      }
     ]
    },
    {
     "title": "Eventfeed error/m",
     "type": "graph",
     "description": "The number of errors that interrupt Eventfeed RPC",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tikv_cdc_kvclient_event_feed_error_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "-sum(increase(pd_schedule_operators_count{tidb_cluster=\"$tidb_cluster\", event=\"create\", type=~\".*leader\"}[1m]))",
       "legendFormat": "transfer-leader"
      },
      {
       "expr": "-sum(increase(pd_schedule_operators_count{tidb_cluster=\"$tidb_cluster\", event=\"create\", type=~\".*(peer|region)\"}[1m]))",
       "legendFormat": "move-region"
      }
     ]
    },
    {
     "title": "KV client receive events/s",
     "type": "graph",
     "description": "The number of KV client received events from TiKV per seconds",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_kvclient_pull_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (instance, type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Puller output events/s",
     "type": "graph",
     "description": "The number of events that puller outputs to sorter \n per second",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (rate(tikv_cdc_puller_txn_collect_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (instance, type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Sink buffer size",
     "type": "graph",
     "description": "The number of events that are buffered in Processor's output channel and Sink's input channel",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "-sum(tikv_cdc_sink_buffer_chan_size{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}-sink buffer chan"
      }
     ]
    },
    {
     "title": "Entry sorter sort duration",
     "type": "heatmap",
     "description": "Duration of sorting unsorted events",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_puller_entry_sorter_sort_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Entry sorter sort duration percentile",
     "type": "graph",
     "description": "Percentiles of sorting events duration",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_cdc_puller_entry_sorter_sort_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_puller_entry_sorter_sort_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p95"
      }
     ]
    },
    {
     "title": "Entry sorter merge duration",
     "type": "heatmap",
     "description": "Duration of merging sorted events",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_puller_entry_sorter_merge_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Entry sorter merge duration percentile",
     "type": "graph",
     "description": "Percentiles of merging sorted events duration",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_cdc_puller_entry_sorter_merge_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_puller_entry_sorter_merge_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p95"
      }
     ]
    },
    {
     "title": "KV client dispatch events/s",
     "type": "graph",
     "description": "The number of KV client dispatched event per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_kvclient_send_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (capture, changefeed, type)",
       "legendFormat": "{{capture}}-{{changefeed}}-{{type}}"
      },
      {
       "expr": "sum(rate(tikv_cdc_kvclient_batch_resolved_event_size_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (capture, changefeed, table)",
       "legendFormat": "{{capture}}-{{changefeed}}-batch-resolved"
      }
     ]
    },
    {
     "title": "KV client batch resolved size",
     "type": "heatmap",
     "description": "The size of batch resolved ts message from TiKV",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_kvclient_batch_resolved_event_size_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "KV client scanning regions",
     "type": "graph",
     "description": "The number of regions that are being scanned",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_kvclient_region_token{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}) by (capture, changefeed, store)",
       "legendFormat": "{{changefeed}}-{{capture}}-{{store}}"
      }
     ]
    },
    {
     "title": "KV client gRPC stream count",
     "type": "graph",
     "description": "Active stream count of each gRPC connection",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_kvclient_grpc_stream_count{tidb_cluster=\"$tidb_cluster\"}) by (store)",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "KV client cached regions",
     "type": "graph",
     "description": "The number of regions that have not connected to TiKV",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_kvclient_cached_region{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}) by (capture, changefeed, store)",
       "legendFormat": "{{changefeed}}-{{capture}}-{{store}}"
      }
     ]
    },
    {
     "title": "Estimate remaining time for initialization",
     "type": "graph",
     "description": "Estimate the remaining time for a changefeed initialization (on a specific capture)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "abs(sum(tikv_cdc_kvclient_cached_region{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"} / deriv(tikv_cdc_kvclient_cached_region{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (capture, changefeed, store))",
       "legendFormat": "{{changefeed}}-{{capture}}-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unified Sorter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unified Sorter intake rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_consume_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (capture,changefeed)",
       "legendFormat": "{{capture}}-{{changefeed}}"
      }
     ]
    },
    {
     "title": "Unified Sorter event output rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_event_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (capture,changefeed)",
       "legendFormat": "{{capture}}-{{changefeed}}"
      }
     ]
    },
    {
     "title": "Unified Sorter on disk data size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_sorter_on_disk_data_size_gauge{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Unified Sorter in-memory data size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_sorter_in_memory_data_size_gauge{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    },
    {
     "title": "Unified Sorter flush sizes",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_flush_count_histogram_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Unified Sorter merge size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_sorter_merge_count_histogram_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Etcd MVCC DB total size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{tidb_cluster=\"$tidb_cluster\", job=\"pd\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Etcd health check duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_cdc_server_etcd_health_check_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "p999-{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_server_etcd_health_check_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "p99-{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_server_etcd_health_check_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,instance))",
       "legendFormat": "p95-{{instance}}"
      }
     ]
    },
    {
     "title": "EtcdWorker exec etcd txn duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_etcd_worker_tick_reactor_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "EtcdWorker tick reactor duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_etcd_worker_tick_reactor_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_etcd_worker_tick_reactor_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-99"
      }
     ]
    },
    {
     "title": "EtcdWorker exec etcd txn duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_etcd_worker_etcd_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "EtcdWorker exec etcd txn duration percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_etcd_worker_etcd_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_etcd_worker_etcd_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p99"
      }
     ]
    },
    {
     "title": "EtcdWorker txn size",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_etcd_worker_etcd_txn_size_bytes_bucket{tidb_cluster=\"$tidb_cluster\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "EtcdWorker txn size percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_etcd_worker_etcd_txn_size_bytes_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_etcd_worker_etcd_txn_size_bytes_bucket{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[1m])) by (le,capture))",
       "legendFormat": "{{capture}}-p99"
      }
     ]
    },
    {
     "title": "Etcd 99% WAL fsync duration",
     "type": "graph",
     "description": "The time consumed of writing WAL into the persistent storage in .99",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Etcd 99% Handle transactions duration",
     "type": "graph",
     "description": "The time consumed of handling etcd transactions in .99",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_txn_handle_txns_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\"}[5m])) by (instance, result, le))",
       "legendFormat": "{{instance}} {{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TiKV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CDC CPU",
     "type": "graph",
     "description": "CPU usage of TiKV-CDC component",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", name=~\"cdc_.*|cdc\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-endpoint"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", name=~\"cdcwkr.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-workers"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", name=~\"tso\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-tso"
      }
     ]
    },
    {
     "title": "CDC network traffic",
     "type": "graph",
     "description": "Outbound network traffic of TiKV-CDC component",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_grpc_message_sent_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[30s])) by (instance, type)",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "gRPC message count",
     "type": "graph",
     "description": "The count of different kinds of gRPC message",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", type!=\"kv_gc\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "CDC memory",
     "type": "graph",
     "description": "The memory usage per TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(avg(process_resident_memory_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", job=~\"tikv.*\"}) by (instance)) - (avg(tikv_engine_block_cache_size_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", db=\"kv\"}) by(instance))",
       "legendFormat": "tikv-{{instance}}"
      },
      {
       "expr": "sum(tikv_cdc_sink_memory_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "sink-{{instance}}"
      },
      {
       "expr": "sum(tikv_cdc_old_value_cache_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "old-value-{{instance}}"
      }
     ]
    },
    {
     "title": "Min resolved ts",
     "type": "graph",
     "description": "The min resolved ts of each TiKV",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "scalar(max(pd_cluster_tso{tidb_cluster=\"$tidb_cluster\"}))/1000 - avg(tikv_cdc_min_resolved_ts{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}/1000) by (instance) > 0",
       "legendFormat": "{{instance}}-min-resolved-lag"
      },
      {
       "expr": "max(pd_cluster_tso{tidb_cluster=\"$tidb_cluster\"})",
       "legendFormat": "current-ts"
      },
      {
       "expr": "avg(tikv_cdc_min_resolved_ts{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "{{instance}}-min-resolved-ts"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(tikv_cdc_raw_outlier_resolved_ts_gap_seconds_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}-raw-outlier-region-lag"
      }
     ]
    },
    {
     "title": "Min resolved Region",
     "type": "graph",
     "description": "The ID of the min resolved region of each TiKV",
     "gridPos": { "h": 7, "w": 5, "x": 7, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(tikv_cdc_min_resolved_ts_region{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "{{instance}}-min-resolved-region"
      }
     ]
    },
    {
     "title": "Resolved ts lag duration percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99999, sum(rate(tikv_cdc_resolved_ts_gap_seconds_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}-p9999"
      }
     ]
    },
    {
     "title": "Initial scan duration",
     "type": "heatmap",
     "description": "The time consumed to CDC incremental scan",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_scan_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Initial scan duration percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(tikv_cdc_scan_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}-p9999"
      }
     ]
    },
    {
     "title": "Initial scan tasks status",
     "type": "graph",
     "description": "The number of incremental scan task in different status.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_scan_tasks{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", type=\"ongoing\"}) by (type, instance)",
       "legendFormat": "{{instance}}-{{type}}"
      },
      {
       "expr": "sum(tikv_cdc_scan_tasks{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", type=\"total\"}) by (instance) - sum(tikv_cdc_scan_tasks{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", type=~\"abort|finish\"}) by (instance)",
       "legendFormat": "{{instance}}-pending"
      }
     ]
    },
    {
     "title": "Captured region count",
     "type": "graph",
     "description": "The memory usage per TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(tikv_cdc_captured_region_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "tikv-{{instance}}-total"
      },
      {
       "expr": "sum(tikv_cdc_region_resolve_status{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance, status)",
       "legendFormat": "tikv-{{instance}}-{{status}}"
      }
     ]
    },
    {
     "title": "CDC scan speed",
     "type": "graph",
     "description": "The speed of TiKV-CDC incremental scan",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_scan_bytes_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", job=\"tikv\"}[30s])) by (instance)",
       "legendFormat": "tikv-{{instance}}"
      }
     ]
    },
    {
     "title": "CDC total scan bytes",
     "type": "graph",
     "description": "The total bytes of TiKV-CDC incremental scan",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_scan_bytes_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\", job=\"tikv\"}) by (instance)",
       "legendFormat": "tikv-{{instance}}"
      }
     ]
    },
    {
     "title": "Old value cache hit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(tikv_cdc_old_value_cache_access{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance) - sum(rate(tikv_cdc_old_value_cache_miss{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance)) / sum(rate(tikv_cdc_old_value_cache_access{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance)",
       "legendFormat": "hit-rate-{{instance}}"
      },
      {
       "expr": "-sum(rate(tikv_cdc_old_value_cache_miss{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance)",
       "legendFormat": "miss-{{instance}}"
      },
      {
       "expr": "-sum(rate(tikv_cdc_old_value_cache_miss_none{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance)",
       "legendFormat": "miss-none-{{instance}}"
      }
     ]
    },
    {
     "title": "Old value cache size",
     "type": "graph",
     "description": "The total number of cache entries in the old value cache.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_old_value_cache_length{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "{{instance}}-len"
      },
      {
       "expr": "sum(tikv_cdc_old_value_cache_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance) / sum(tikv_cdc_old_value_cache_length{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "{{instance}}-avg entry bytes"
      },
      {
       "expr": "sum(tikv_cdc_old_value_cache_memory_quota{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}) by (instance)",
       "legendFormat": "{{instance}}-quota"
      }
     ]
    },
    {
     "title": "Old value seek operation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_old_value_scan_details{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (instance, cf, tag)",
       "legendFormat": "{{instance}}-{{cf}}-{{tag}}"
      }
     ]
    },
    {
     "title": "Old value seek duration",
     "type": "heatmap",
     "description": "The time consumed to get an old value (both from cache and from disk)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_old_value_duration_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Old value seek duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_old_value_duration_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance, tag))",
       "legendFormat": "{{instance}}-99%-{{tag}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_old_value_duration_bucket{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance, tag))",
       "legendFormat": "{{instance}}-95%-{{tag}}"
      },
      {
       "expr": "sum(rate(tikv_cdc_old_value_duration_sum{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance, tag) / sum(rate(tikv_cdc_old_value_duration_count{tidb_cluster=\"$tidb_cluster\", instance=~\"$tikv_instance\"}[1m])) by (le, instance, tag)",
       "legendFormat": "{{instance}}-avg-{{tag}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Peer Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Receive Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (from) (rate(tikv_cdc_message_server_message_count{instance=~\"$capture\"}[30s]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Message Send Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (to) (rate(tikv_cdc_message_client_message_count{instance=~\"$capture\"}[30s]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Message Batch Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(tikv_cdc_message_server_message_batch_size_bucket[30s])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_message_server_message_batch_size_bucket[30s])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_message_server_message_batch_size_bucket[30s])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Receive message batch bytes percentiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(tikv_cdc_message_server_message_batch_bytes_bucket [30s])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_message_server_message_batch_bytes_bucket [30s])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_message_server_message_batch_bytes_bucket [30s])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Receive Message Bytes Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(tikv_cdc_message_server_message_bytes_bucket [30s])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_message_server_message_bytes_bucket [30s])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_message_server_message_bytes_bucket [30s])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Stream Count Between Nodes",
     "type": "table",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "tikv_cdc_message_server_cur_stream_count"
      }
     ]
    },
    {
     "title": "Total Stream Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tikv_cdc_message_server_cur_stream_count)",
       "legendFormat": "actual"
      },
      {
       "expr": "2 * count(process_start_time_seconds{tidb_cluster=\"$tidb_cluster\", job=\"tikv-cdc\"}) - 1",
       "legendFormat": "expected"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime $runtime_instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "runtime_instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "TiKV-CDC process rss memory usage. TiKV-CDC heap memory size in use ",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}",
       "legendFormat": "alloc-from-os"
      },
      {
       "expr": "go_memstats_next_gc_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} / (1 + tikv_cdc_server_go_gc{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} / 100)",
       "legendFormat": "estimate-inuse"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} - go_memstats_next_gc_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} / (1 + tikv_cdc_server_go_gc{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} / 100)",
       "legendFormat": "estimate-garbage"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} - go_memstats_heap_released_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} + go_memstats_heap_inuse_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} - go_memstats_heap_alloc_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}",
       "legendFormat": "reserved-by-go"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} + go_memstats_mspan_sys_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} + go_memstats_mcache_sys_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} + go_memstats_buck_hash_sys_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} + go_memstats_gc_sys_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} + go_memstats_other_sys_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}",
       "legendFormat": "used-by-go"
      },
      {
       "expr": "go_memstats_next_gc_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}",
       "legendFormat": "gc-threshold"
      },
      {
       "expr": "(clamp_max(idelta(go_memstats_last_gc_time_seconds{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}[1m]), 1) * go_memstats_next_gc_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}) > 0",
       "legendFormat": "gc"
      }
     ]
    },
    {
     "title": "Estimated Live Objects",
     "type": "graph",
     "description": "Count of live objects.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}",
       "legendFormat": "objects"
      }
     ]
    },
    {
     "title": "GC STW Duration (last 256 GC cycles)",
     "type": "graph",
     "description": "TiKV-CDC process Go garbage collection STW pause duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\", quantile=\"0\"}",
       "legendFormat": "min"
      },
      {
       "expr": "go_gc_duration_seconds{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\", quantile!~\"0|1\"}",
       "legendFormat": "{{quantile}}"
      },
      {
       "expr": "go_gc_duration_seconds{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\", quantile=\"1\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Allocator Throughput",
     "type": "graph",
     "description": "The throughput of Go's memory allocator.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(go_memstats_alloc_bytes_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}[30s])",
       "legendFormat": "alloc"
      },
      {
       "expr": "irate((go_memstats_alloc_bytes_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"} - go_memstats_heap_alloc_bytes{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"})[30s:])",
       "legendFormat": "sweep"
      },
      {
       "expr": "irate(go_memstats_mallocs_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}[30s])",
       "legendFormat": "alloc-ops"
      },
      {
       "expr": "irate(go_memstats_frees_total{tidb_cluster=\"$tidb_cluster\", instance=~\"$runtime_instance\"}[30s])",
       "legendFormat": "swepp-ops"
      }
     ]
    }
   ]
  },
  {
   "title": "Redo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redo fsync duration",
     "type": "heatmap",
     "description": "The latency distributions of fsync called by redo writer",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "max(rate(tikv_cdc_redo_fsync_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Redo flushall duration",
     "type": "heatmap",
     "description": "The latency distributions of flushall called by redo writer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "max(rate(tikv_cdc_redo_flushall_duration_seconds_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Redo Write rows/s ",
     "type": "graph",
     "description": "The total count of rows that are processed by redo writer",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_redo_total_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}"
      },
      {
       "expr": "sum(rate(tikv_cdc_redo_total_rows_count{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (changefeed)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Redo Write bytes/s ",
     "type": "graph",
     "description": "Total number of bytes redo log written",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_cdc_redo_write_bytes_total{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",capture=~\"$capture\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TiKV Sink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "TiKV sink write duration percentile",
     "type": "graph",
     "description": "Percentiles of TiKV sink write duration by each server.\n",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_cdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\", type=\"TiKV\"}[1m])) by (le,instance, changefeed))",
       "legendFormat": "{{changefeed}}-{{instance}}-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\", type=\"TiKV\"}[1m])) by (le,instance, changefeed))",
       "legendFormat": "{{changefeed}}-{{instance}}-p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_cdc_sink_txn_exec_duration_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\", type=\"TiKV\"}[1m])) by (le,instance, changefeed))",
       "legendFormat": "{{changefeed}}-{{instance}}-p999"
      }
     ]
    },
    {
     "title": "TiKV sink write batch size percentile",
     "type": "graph",
     "description": "Percentiles of sink batch size",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(tikv_cdc_sink_txn_batch_size_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\", type=\"TiKV\"}[1m])) by (le, instance, changefeed))",
       "legendFormat": "{{changefeed}}-{{instance}}-p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_cdc_sink_txn_batch_size_bucket{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\", type=\"TiKV\"}[1m])) by (le, instance, changefeed))",
       "legendFormat": "{{changefeed}}-{{instance}}-p99"
      }
     ]
    },
    {
     "title": "TiKV sink write rows count/s",
     "type": "graph",
     "description": "The number of changed entires that are written to  downstream TiKV",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (rate(tikv_cdc_sink_txn_batch_size_sum{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\", type=\"TiKV\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum (rate(tikv_cdc_sink_txn_batch_size_sum{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\", type=\"TiKV\"}[1m])) by (changefeed)",
       "legendFormat": "{{changefeed}}"
      }
     ]
    },
    {
     "title": "TiKV sink error count/m",
     "type": "graph",
     "description": "The number of errors that interrupt changefeed per minute ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(tikv_cdc_sink_execution_error{tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", capture=~\"$capture\", type=\"TiKV\"}[1m])) by (capture)",
       "legendFormat": "{{capture}}"
      }
     ]
    }
   ]
  }
 ]
}