# Importer Configuration.

name = "gc-worker0"

pd = ""
etcd = ""
safepoint-update-interval = "10s"
etcd-election-interval = "10ms"
gc-life-time = "10m"

[security]
ca = "abc"
cert = "def"
key = "hij"

[log]
level = "info"
# log format, one of json, text, console
format = "text"

[log.file]
# Usually it is set through command line.
filename = "gc_worker.log"
# max log file size in MB
max-size = 300
# max log file keep days
max-days = 0
# maximum number of old log files to retain
max-backups = 0
