#!/bin/bash
# parameter 1: work directory
# parameter 2: dst pd
# parameter 3: total kvs
# parameter 4: max check times

CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
TLS_DIR=$(cd $CUR/../_certificates && pwd)

workdir=$1
DOWN_PD=$2
TOTAL_KVS=$3
if [ $# -ge 4 ]; then
	check_time=$4
else
	check_time=50
fi
PWD=$(pwd)

if ! command -v rawkv_data &>/dev/null; then
	cd $CUR/../../..
	make rawkv_data
	cd $PWD
fi
set +e

cd $workdir
i=0
while [ $i -lt $check_time ]; do
	rm -rf $workdir/rawkv_data/
	rawkv_data totalkvs --dst-pd $DOWN_PD --count $TOTAL_KVS --ca-path=$TLS_DIR/ca.pem --cert-path=$TLS_DIR/client.pem --key-path=$TLS_DIR/client-key.pem
	ret=$?
	if [ "$ret" == 0 ]; then
		echo "check total-kvs successfully"
		break
	fi
	((i++))
	echo "check total-kvs failed $i-th time, retry later"
	sleep 3
done

if [ $i -ge $check_time ]; then
	echo "check total-kvs failed at last"
	exit 1
fi

cd $PWD
