#!/bin/bash
# parameter 1: work directory
# parameter 2: src pd
# parameter 3: dst pd
# parameter 4: max check times

CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
binary=$CUR/../../utils/rawkv_data/rawkv_data
PWD=$(pwd)
if [ ! -f $binary ]; then
	cd $CUR/../../utils/rawkv_data/
	GO111MODULE=on go build
	cd $PWD
fi

workdir=$1
UP_PD=$2
DOWN_PD=$3
if [ $# -ge 4 ]; then
	check_time=$4
else
	check_time=30
fi

cd $workdir
i=0
while [ $i -lt $check_time ]; do
	rm -rf $workdir/rawkv_data/
	$binary checksum --src-pd $UP_PD --dst-pd $DOWN_PD
	ret=$?
	if [ "$ret" == 0 ]; then
		echo "check diff successfully"
		break
	fi
	((i++))
	echo "check diff failed $i-th time, retry later"
	sleep 5
done

if [ $i -ge $check_time ]; then
	echo "check diff failed at last"
	exit 1
fi

cd $PWD
