#!/bin/bash

# In TiKV with ApiV2 will cache a lot of tso to append to key.
# If we query a tso from pd, and use it as start-ts, the start-ts will be greater than 
# the tso than TiKV cached. So we need to fallback ts 10s.

# parameter 1: pd_addr

FALLBACK=2621440000

set -euo pipefail

tso=$(tikv-cdc cli tso query --pd=$1)
expr $tso - $FALLBACK

