#!/bin/sh
# parameter 1: pd_addr
# parameter 2: put/delete
# parameter 3: key count

set -e

CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PWD=$(pwd)

cd $CUR/../../utils/rawkv_data
if [ ! -f ./rawkv_data ]; then
	GO111MODULE=on go build
fi

./rawkv_data $2 --src-pd $1 --count $3

cd $PWD
