#!/bin/bash
# parameter 1: pd_addr
# parameter 2: put/delete
# parameter 3: key count

CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
TLS_DIR=$(cd $CUR/../_certificates && pwd)
set -e

if ! command -v rawkv_data &>/dev/null; then
	echo "make rawkv_data"
	PWD=$(pwd)
	cd $CUR/../../..
	make rakv_data
	cd $PWD
fi

echo "run put data"
rawkv_data $2 --src-pd $1 --count $3 --ca-path=$TLS_DIR/ca.pem --cert-path=$TLS_DIR/client.pem --key-path=$TLS_DIR/client-key.pem
