#!/bin/bash
#
# Copyright 2020 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Clone from https://github.com/pingcap/tidb/blob/master/br/tests/_utils/run_curl

# Usage: run_curl https://url '{"json":"data"}'

set -eu

CUR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
TLS_DIR=$(cd $CUR/../_certificates && pwd)

if [ -z "${2-}" ]; then
	POST_ARGS=
else
	POST_ARGS="--post-data $2"
fi

# FIXME: use `wget` instead of `curl` because the latter rejects ECC certs on our CI.
# CentOS is re~~ally old.
wget -q -O - \
	--ca-certificate="$TLS_DIR/ca.pem" \
	--certificate="$TLS_DIR/server.pem" \
	--private-key="$TLS_DIR/server-key.pem" \
	$POST_ARGS "$1"
