package model

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

var (
	op_type    = generateFeildName("op_type")
	key        = generateFeildName("key")
	value      = generateFeildName("value")
	old_value  = generateFeildName("old_value")
	start_ts   = generateFeildName("start_ts")
	crts       = generateFeildName("crts")
	expired_ts = generateFeildName("expired_ts")
	region_id  = generateFeildName("region_id")
	keyspan_id = generateFeildName("keyspan_id")
)

// DecodeMsg implements msgp.Decodable
func (z *OpType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int
		zb0001, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = OpType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z OpType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt(int(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z OpType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt(o, int(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *OpType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int
		zb0001, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = OpType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z OpType) Msgsize() (s int) {
	s = msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RawKVEntry) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "op_type":
			{
				var zb0002 int
				zb0002, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "OpType")
					return
				}
				z.OpType = OpType(zb0002)
			}
		case "key":
			z.Key, err = dc.ReadBytes(z.Key)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "value":
			z.Value, err = dc.ReadBytes(z.Value)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "old_value":
			z.OldValue, err = dc.ReadBytes(z.OldValue)
			if err != nil {
				err = msgp.WrapError(err, "OldValue")
				return
			}
		case "start_ts":
			z.StartTs, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "StartTs")
				return
			}
		case "crts":
			z.CRTs, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "CRTs")
				return
			}
		case "expired_ts":
			z.ExpiredTs, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ExpiredTs")
				return
			}
		case "region_id":
			z.RegionID, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "RegionID")
				return
			}
		case "keyspan_id":
			z.KeySpanID, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "KeySpanID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RawKVEntry) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	err = en.Append(0x89)
	if err != nil {
		return
	}
	// write "op_type"
	err = en.Append(op_type...)
	if err != nil {
		return
	}
	err = en.WriteInt(int(z.OpType))
	if err != nil {
		err = msgp.WrapError(err, "OpType")
		return
	}
	// write "key"
	err = en.Append(key...)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Key)
	if err != nil {
		err = msgp.WrapError(err, "Key")
		return
	}
	// write "value"
	err = en.Append(value...)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	// write "old_value"
	err = en.Append(old_value...)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.OldValue)
	if err != nil {
		err = msgp.WrapError(err, "OldValue")
		return
	}
	// write "start_ts"
	err = en.Append(start_ts...)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.StartTs)
	if err != nil {
		err = msgp.WrapError(err, "StartTs")
		return
	}
	// write "crts"
	err = en.Append(crts...)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.CRTs)
	if err != nil {
		err = msgp.WrapError(err, "CRTs")
		return
	}
	// write "expired_ts"
	err = en.Append(expired_ts...)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.ExpiredTs)
	if err != nil {
		err = msgp.WrapError(err, "ExpiredTs")
		return
	}
	// write "region_id"
	err = en.Append(region_id...)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.RegionID)
	if err != nil {
		err = msgp.WrapError(err, "RegionID")
		return
	}
	// write "keyspan_id"
	err = en.Append(keyspan_id...)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.KeySpanID)
	if err != nil {
		err = msgp.WrapError(err, "KeySpanID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RawKVEntry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	o = append(o, 0x89)
	// string "op_type"
	o = append(o, op_type...)
	o = msgp.AppendInt(o, int(z.OpType))
	// string "key"
	o = append(o, key...)
	o = msgp.AppendBytes(o, z.Key)
	// string "value"
	o = append(o, value...)
	o = msgp.AppendBytes(o, z.Value)
	// string "old_value"
	o = append(o, old_value...)
	o = msgp.AppendBytes(o, z.OldValue)
	// string "start_ts"
	o = append(o, start_ts...)
	o = msgp.AppendUint64(o, z.StartTs)
	// string "crts"
	o = append(o, crts...)
	o = msgp.AppendUint64(o, z.CRTs)
	// string "expired_ts"
	o = append(o, expired_ts...)
	o = msgp.AppendUint64(o, z.ExpiredTs)
	// string "region_id"
	o = append(o, region_id...)
	o = msgp.AppendUint64(o, z.RegionID)
	// string "keyspan_id"
	o = append(o, keyspan_id...)
	o = msgp.AppendUint64(o, z.KeySpanID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RawKVEntry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "op_type":
			{
				var zb0002 int
				zb0002, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "OpType")
					return
				}
				z.OpType = OpType(zb0002)
			}
		case "key":
			z.Key, bts, err = msgp.ReadBytesBytes(bts, z.Key)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "value":
			z.Value, bts, err = msgp.ReadBytesBytes(bts, z.Value)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "old_value":
			z.OldValue, bts, err = msgp.ReadBytesBytes(bts, z.OldValue)
			if err != nil {
				err = msgp.WrapError(err, "OldValue")
				return
			}
		case "start_ts":
			z.StartTs, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StartTs")
				return
			}
		case "crts":
			z.CRTs, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CRTs")
				return
			}
		case "expired_ts":
			z.ExpiredTs, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpiredTs")
				return
			}
		case "region_id":
			z.RegionID, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RegionID")
				return
			}
		case "keyspan_id":
			z.KeySpanID, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "KeySpanID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RawKVEntry) Msgsize() (s int) {
	s = 1 + 8 + msgp.IntSize + 4 + msgp.BytesPrefixSize + len(z.Key) + 6 + msgp.BytesPrefixSize + len(z.Value) + 10 + msgp.BytesPrefixSize + len(z.OldValue) + 9 + msgp.Uint64Size + 5 + msgp.Uint64Size + 11 + msgp.Uint64Size + 10 + msgp.Uint64Size + 11 + msgp.Uint64Size
	return
}

func generateFeildName(feildName string) (bytes []byte) {
	l := len(feildName)
	bytes = make([]byte, 0, l+1)
	bytes = append(bytes, 0xa0+byte(l))
	bytes = append(bytes, []byte(feildName)...)
	return
}
