[sink]
# 对于 MQ 类的 Sink，可以通过 dispatchers 配置 event 分发器
# 分发器支持 default, ts, rowid, table 四种
# For MQ Sinks, you can configure event distribution rules through dispatchers
# Dispatchers support default, ts, rowid and table
dispatchers = [
    { matcher = ['test1.*', 'test2.*'], dispatcher = "ts" },
    { matcher = ['test3.*', 'test4.*'], dispatcher = "rowid" },
]
# 对于 MQ 类的 Sink，可以通过 column-selectors 配置 column 选择器
# For MQ Sinks, you can configure column selector rules through column-selectors
column-selectors = [
    { matcher = ['test1.*', 'test2.*'], columns = ["column1", "column2"] },
    { matcher = ['test3.*', 'test4.*'], columns = ["!a", "column3"] },
]
# 对于 MQ 类的 Sink，可以指定消息的协议格式
# 协议目前支持 open-protocol, canal, canal-json, avro 和 maxwell 五种。
# For MQ Sinks, you can configure the protocol of the messages sending to MQ
# Currently the protocol support open-protocol, canal, canal-json, avro and maxwell.
protocol = "open-protocol"
