name: TiKV-CDC

on:
  push:
    branches:
      - main
    paths:
      - "cdc/**"
      - ".github/workflows/ci-cdc.yml"
  pull_request:
    branches:
      - main
    paths:
      - "cdc/**"
      - ".github/workflows/ci-cdc.yml"

permissions:
  contents: read

concurrency:
  group: ci-cdc-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.21.4

defaults:
  run:
    shell: bash
    working-directory: cdc

jobs:
  cdc-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache-dependency-path: cdc/go.sum
      - name: make check
        run: make check
  cdc-check-gosec:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache-dependency-path: cdc/go.sum
      - name: make check-gosec
        run: make check-gosec
  cdc-build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache-dependency-path: cdc/go.sum
      - name: make cdc
        run: make cdc
  cdc-unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache-dependency-path: cdc/go.sum
      - name: make unit_test_in_verify_ci
        env:
          TIKV_MIGRATION_CODECOV_TOKEN: ${{ secrets.TIKV_MIGRATION_CODECOV_TOKEN }}
        run: make unit_test_in_verify_ci
